# Site
name: "Security Insights: Lightweight Crypto, FIPS, AI/ML"
description: "Stay updated on security trends with a focus on Lightweight Crypto, FIPS compliance, and AI/ML advancements."
logo: 'assets/images/tlsweight_log.png'
favicon: 'assets/images/favicon_package_v0.16/favicon.ico'
baseurl: ''
disqus: 'tlsweight'
email: 'vkosuri@tlsweight.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-toc

authors:
    vkosuri:
      name:           vkosuri
      site:           https://vkosuri.github.io/
      avatar:         assets/images/avatar.jpg
      bio:            "I'm a security product enthusiast, constantly exploring new ideas and documenting my journey. While I'm not a native English speaker, I'm passionate about the world of security and eager to contribute to its evolution."
      email:          malli.kv2@gmail.com
      twitter:        https://twitter.com/mallikarjunarao
      linkdin:        https://www.linkedin.com/in/mallikarjunaraok/
      github:         https://github.com/vkosuri
      youtube:        https://www.youtube.com/user/mallikv


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: vkosuri
      avatar: assets/images/avatar.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge


# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
